# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
if [ -f "${HOME}/.bash_aliases" ]; then
  source "${HOME}/.bash_aliases"
fi

PATH=$HOME/bin:$PATH

# added by Anaconda3 2.4.1 installer
export PATH="/home/mroses43@ad.avant.com/anaconda3/bin:$PATH"
export looker="/home/mroses43@ad.avant.com/avant-strategy/us_payments/reporting/looker"

#PYTHONPATH="${PYTHONPATH}:/Users/mroses43/avant-python-utils"
#export PYTHONPATH

export ACQUEON_SERVER="10.12.4.235"
export ACQUEON_PORT="1433"
export ACQUEON_PW="kamaal da Database ho 22g!"
export ACQUEON_USER="acqueon"

# source ~/.bash-powerline.sh

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

. $HOME/z/z.sh
